local wezterm = require 'wezterm'
local module = {}

local act = wezterm.action

local activateResizePaneOpt = {
    name = 'resize_pane',
    timeout_milliseconds = 500,
    one_shot = false,
    replace_current = true,
    prevent_fallback = true,
}

local options = {
    keys = {
        -- Disable default keybinds
        { key = 'Tab', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'Tab', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '!', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '!', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '\"', mods = 'ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '\"', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '#', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '#', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '$', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '$', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '%', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '%', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '%', mods = 'ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '%', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '&', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '&', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '\'', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '(', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '(', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = ')', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = ')', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '*', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '*', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '+', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '+', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '-', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '-', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '0', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '0', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '1', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '2', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '3', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '4', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '5', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '5', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = '6', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '7', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '8', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '9', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '=', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '=', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '@', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '@', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'C', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'C', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'F', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'F', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'H', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'H', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'K', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'K', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'L', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'L', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'M', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'M', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'N', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'N', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'P', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'P', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'Q', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'Q', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'R', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'R', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'T', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'T', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'U', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'U', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'V', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'V', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'W', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'W', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'X', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'X', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'Z', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'Z', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '^', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '^', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '_', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = '_', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'c', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'f', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'h', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'k', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'k', mods = 'SUPER', action = act.DisableDefaultAssignment },
        { key = 'l', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'm', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'n', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'p', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'q', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'r', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 't', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'u', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'v', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'w', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'x', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'z', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = '{', mods = 'SUPER', action = act.DisableDefaultAssignment },
        { key = '{', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
        { key = '}', mods = 'SUPER', action = act.DisableDefaultAssignment },
        { key = '}', mods = 'SHIFT|SUPER', action = act.DisableDefaultAssignment },
        { key = 'phys:Space', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'PageUp', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'PageUp', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'PageDown', mods = 'CTRL', action = act.DisableDefaultAssignment },
        { key = 'PageDown', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'LeftArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'LeftArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'RightArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'RightArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'UpArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'UpArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'DownArrow', mods = 'SHIFT|CTRL', action = act.DisableDefaultAssignment },
        { key = 'DownArrow', mods = 'SHIFT|ALT|CTRL', action = act.DisableDefaultAssignment },

        -- Setting keybinds
        { key = '-', mods = 'SUPER', action = act.DecreaseFontSize },
        { key = '0', mods = 'SUPER', action = act.ResetFontSize },
        { key = '1', mods = 'SUPER', action = act.ActivateTab(0) },
        { key = '2', mods = 'SUPER', action = act.ActivateTab(1) },
        { key = '3', mods = 'SUPER', action = act.ActivateTab(2) },
        { key = '4', mods = 'SUPER', action = act.ActivateTab(3) },
        { key = '5', mods = 'SUPER', action = act.ActivateTab(4) },
        { key = '6', mods = 'SUPER', action = act.ActivateTab(5) },
        { key = '7', mods = 'SUPER', action = act.ActivateTab(6) },
        { key = '8', mods = 'SUPER', action = act.ActivateTab(7) },
        { key = '9', mods = 'SUPER', action = act.ActivateTab(-1) },
        { key = ';', mods = 'ALT|SUPER', action = act.PaneSelect { mode = 'SwapWithActive' } },
        { key = ';', mods = 'SUPER', action = act.PaneSelect },
        { key = '=', mods = 'SUPER', action = act.IncreaseFontSize },
        { key = '[', mods = 'ALT|SUPER', action = act.MoveTabRelative(-1) },
        { key = '[', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(-1) },
        { key = '\'', mods = 'SUPER', action = act.ShowTabNavigator },
        { key = ']', mods = 'ALT|SUPER', action = act.MoveTabRelative(1) },
        { key = ']', mods = 'SHIFT|SUPER', action = act.ActivateTabRelative(1) },
        { key = 'c', mods = 'SUPER', action = act.CopyTo 'Clipboard' },
        { key = 'f', mods = 'SUPER', action = act.Search 'CurrentSelectionOrEmptyString' },
        { key = 'h', mods = 'SUPER', action = act.HideApplication },
        { key = 'm', mods = 'SUPER', action = act.Hide },
        { key = 'n', mods = 'SUPER', action = act.SpawnWindow },
        { key = 'p', mods = 'SHIFT|SUPER', action = act.ActivateCommandPalette },
        { key = 'p', mods = 'SUPER', action = act.ActivateKeyTable { name = 'pane_mode', one_shot = true, prevent_fallback = true } },
        { key = 'q', mods = 'SUPER', action = act.QuitApplication },
        { key = 'r', mods = 'SUPER', action = act.ReloadConfiguration },
        { key = 's', mods = 'SUPER', action = act.QuickSelect },
        { key = 't', mods = 'SUPER', action = act.SpawnTab 'CurrentPaneDomain' },
        { key = 'v', mods = 'SUPER', action = act.PasteFrom 'Clipboard' },
        { key = 'w', mods = 'SUPER', action = act.CloseCurrentTab{ confirm = true } },
        { key = 'y', mods = 'SUPER', action = act.ActivateCopyMode },
        { key = 'Copy', mods = 'NONE', action = act.CopyTo 'Clipboard' },
        { key = 'Enter', mods = 'ALT', action = act.ToggleFullScreen },
        { key = 'PageDown', mods = 'SHIFT', action = act.ScrollByPage(1) },
        { key = 'PageUp', mods = 'SHIFT', action = act.ScrollByPage(-1) },
        { key = 'Paste', mods = 'NONE', action = act.PasteFrom 'Clipboard' },
    },

    key_tables = {
        pane_mode = {
            -- Split pane
            { key = 'h', action = act.SplitPane { direction = 'Left' } },
            { key = 'j', action = act.SplitPane { direction = 'Down' } },
            { key = 'k', action = act.SplitPane { direction = 'Up' } },
            { key = 'l', action = act.SplitPane { direction = 'Right' } },

            -- Select pane
            { key = ';', mods = 'NONE', action = act.PaneSelect },
            { key = ';', mods = 'SUPER', action = act.PaneSelect },
            { key = ';', mods = 'ALT|SUPER', action = act.PaneSelect { mode = 'SwapWithActive' } },

            -- Resize pane
            { key = 'h', mods = 'CTRL', action = act.Multiple {
                act.AdjustPaneSize { 'Left', 1 },
                act.ActivateKeyTable(activateResizePaneOpt),
            }},
            { key = 'j', mods = 'CTRL', action = act.Multiple {
                act.AdjustPaneSize { 'Down', 1 },
                act.ActivateKeyTable(activateResizePaneOpt),
            }},
            { key = 'k', mods = 'CTRL', action = act.Multiple {
                act.AdjustPaneSize { 'Up', 1 },
                act.ActivateKeyTable(activateResizePaneOpt),
            }},
            { key = 'l', mods = 'CTRL', action = act.Multiple {
                act.AdjustPaneSize { 'Right', 1 },
                act.ActivateKeyTable(activateResizePaneOpt),
            }},

            { key = 'x', action = act.CloseCurrentPane { confirm = true } },

            { key = 'q', mods = 'SUPER', action = act.QuitApplication },
            { key = 'Escape', action = 'PopKeyTable' },
        },

        resize_pane = {
            { key = 'h', action = act.AdjustPaneSize { 'Left', 1 } },
            { key = 'h', mods = 'CTRL', action = act.AdjustPaneSize { 'Left', 1 } },
            { key = 'j', action = act.AdjustPaneSize { 'Down', 1 } },
            { key = 'j', mods = 'CTRL', action = act.AdjustPaneSize { 'Down', 1 } },
            { key = 'k', action = act.AdjustPaneSize { 'Up', 1 } },
            { key = 'k', mods = 'CTRL', action = act.AdjustPaneSize { 'Up', 1 } },
            { key = 'l', action = act.AdjustPaneSize { 'Right', 1 } },
            { key = 'l', mods = 'CTRL', action = act.AdjustPaneSize { 'Right', 1 } },

            { key = 'h', mods = 'SHIFT', action = act.AdjustPaneSize { 'Left', 3 } },
            { key = 'j', mods = 'SHIFT', action = act.AdjustPaneSize { 'Down', 3 } },
            { key = 'k', mods = 'SHIFT', action = act.AdjustPaneSize { 'Up', 3 } },
            { key = 'l', mods = 'SHIFT', action = act.AdjustPaneSize { 'Right', 3 } },

            { key = 'Escape', action = 'PopKeyTable' },
        },
    }
}

function module.apply_to_config(config)
    for k, v in pairs(options) do
        config[k] = v
    end
end

return module

