# Documentation: https://sheldon.cli.rs/Introduction.html

shell = 'zsh'

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
# version 0.7.4 or later
# defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.zsh-vi-mode]
github = 'jeffreytse/zsh-vi-mode'
tag = 'v0.11.0'
hooks.pre = '''
    function zvm_config() {
        ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
        ZVM_LAZY_KEYBINDINGS=true
    }

    # 遅延キーバインドが有効になっている場合、normalとvisualモードにキーバインドしたい場合はこの関数内でbindする。
    # function zvm_after_lazy_keybindings() {

    # }

    # zsh-vi-modeがモード変更したときに実行される関数
    function zvm_after_select_vi_mode() {
        #プロンプトに現在のコマンドモードを表示する用の変数
        typeset -g mode_stat
        case $ZVM_MODE in
            $ZVM_MODE_NORMAL)
                mode_stat='n'
                ;;
            $ZVM_MODE_INSERT)
                mode_stat=' '
                ;;
            $ZVM_MODE_VISUAL)
                mode_stat='v'
                ;;
            $ZVM_MODE_VISUAL_LINE)
                mode_stat='V'
                ;;
            $ZVM_MODE_REPLACE)
                mode_stat='r'
                ;;
        esac
    }
'''

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['defer']

[plugins.syntax-highlight]
github = 'zsh-users/zsh-syntax-highlighting'
tag = '0.8.0'
apply = ['defer']
hooks.pre = '''
    zsh-defer -p source "$SHELDON_CONFIG_DIR/zsh-syntax-highlight-settings.zsh"
'''
